USE FLOWERDB

CREATE TABLE Categorytlb
(

CategoryId INT PRIMARY KEY IDENTITY (1,1),
CategoryName VARCHAR(100) NOT NULL,
CategoryImageURL VARCHAR(MAX) NOT NULL,
IsActive BIT NOT NULL,
CreatedDate DATETIME NOT NULL

)


CREATE TABLE SubCategorytlb
(

SubCategoryId INT PRIMARY KEY IDENTITY (1,1),
SubCategoryName VARCHAR(100) NOT NULL,
CategoryId INT FOREIGN KEY REFERENCES Categorytlb(CategoryId) ON DELETE CASCADE NOT NULL, 
IsActive BIT NOT NULL,
CreatedDate DATETIME NOT NULL

)

CREATE TABLE Producttlb

(

ProductId INT PRIMARY KEY IDENTITY (1,1),
ProductName VARCHAR(100) NOT NULL,
ShortDescription VARCHAR(200)  NULL,
LongDescription VARCHAR(MAX) NULL,
AdditionalDecription VARCHAR(MAX) NULL,
Price DECIMAL (18,2) NOT NULL,
Quantity INT NOT NULL,
Color VARCHAR(30) NULL,
CategoryId INT FOREIGN KEY REFERENCES Categorytlb(CategoryId) ON DELETE CASCADE NOT NULL, 
SubCategoryId INT NOT NULL, 
Sold INT NULL, 
IsCustomized BIT NOT NULL, 
IsActive BIT NOT NULL,
CreatedDate DATETIME NOT NULL

)

CREATE TABLE ProductImagetlb
(

ImageId INT PRIMARY KEY IDENTITY (1,1),
ImageURL VARCHAR(MAX) NULL,
ProductId INT FOREIGN KEY REFERENCES Producttlb(ProductId) ON DELETE CASCADE NOT NULL, 
DefualtImage BIT NULL

)

CREATE TABLE Usertlb

(

UserId INT PRIMARY KEY IDENTITY (1,1),
CusName VARCHAR(50)  NULL,
Username VARCHAR(50) NULL,
Mobile VARCHAR(20)  NULL,
Email VARCHAR(50)  NULL,
Address VARCHAR(MAX)  NULL,
PostCode VARCHAR(50)  NULL,
Password VARCHAR(50)  NULL,
ImageUrl VARCHAR(MAX)  NULL,
CreatedDate DATETIME NOT NULL,
)

CREATE TABLE ProductReviewtlb

(

ReviewId INT PRIMARY KEY IDENTITY (1,1),
Rating INT NOT NULL,
Comment VARCHAR(MAX) NULL,
ProductId INT FOREIGN KEY REFERENCES Producttlb(ProductId) ON DELETE CASCADE NOT NULL,
CreatedDate DATETIME NOT NULL


)

CREATE TABLE Wishlist
(

WishlistId INT PRIMARY KEY IDENTITY (1,1),
ProductId INT FOREIGN KEY REFERENCES Producttlb(ProductId) ON DELETE CASCADE NOT NULL,
UserId INT FOREIGN KEY REFERENCES Usertlb(UserId) ON DELETE CASCADE NOT NULL,
CreatedDate DATETIME NOT NULL 

)


CREATE TABLE CART
(

CartId INT PRIMARY KEY IDENTITY (1,1),
ProductId INT FOREIGN KEY REFERENCES Producttlb(ProductId) ON DELETE CASCADE NOT NULL,
Quantity INT NULL,
UserId INT FOREIGN KEY REFERENCES Usertlb(UserId) ON DELETE CASCADE NOT NULL,
CreatedDate DATETIME NOT NULL 

)



CREATE TABLE Contacttlb

(

ContactId INT PRIMARY KEY IDENTITY (1,1),
Name VARCHAR(50) NULL,
Email VARCHAR(50) NULL,
Subject VARCHAR(200) NULL,
Message VARCHAR(MAX) NULL,
CreatedDate DATETIME NOT NULL,
)

CREATE TABLE Paymenttlb

(

PaymentId INT PRIMARY KEY IDENTITY (1,1),
Name VARCHAR(50) NULL,
CardNo VARCHAR(50) NULL,
ExpiryDate VARCHAR(50) NULL,
CvvNo INT NULL,
Address VARCHAR(MAX) NULL,
PaymentMode VARCHAR(50) NULL
)


CREATE TABLE ORDERS

(
OrderDetailsId INT PRIMARY KEY IDENTITY (1,1),
OrderNo VARCHAR(MAX) NULL,
ProductId INT FOREIGN KEY REFERENCES Producttlb(ProductId) ON DELETE CASCADE NOT NULL,
Quantity INT NULL,
UserId INT FOREIGN KEY REFERENCES Usertlb(UserId) ON DELETE CASCADE NOT NULL,
PaymentId INT FOREIGN KEY REFERENCES Paymenttlb(PaymentId) ON DELETE CASCADE NOT NULL,
OrderDate DATETIME NOT NULL,
IsCancel BIT NOT NULL DEFAULT 0

)












