USE FLORISTICDB

CREATE TABLE Categorytlb

(
CategoryId INT PRIMARY KEY IDENTITY (1,1),
CategoryName VARCHAR(100) NOT NULL,
CategoryImageURL VARCHAR(MAX) NOT NULL,
IsActive BIT NOT NULL,
CreatedDate DATETIME NOT NULL

)

